# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'predict.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from sklearn.preprocessing import LabelEncoder

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
import tkinter as tk
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.df = pd.read_excel('thoi_tiet.xlsx')
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1239, 909)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 351, 131))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Pictures/move/logo.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(440, 40, 101, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setUnderline(False)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(0, 140, 1241, 16))
        self.openGLWidget.setObjectName("openGLWidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1120, 30, 81, 71))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../../Pictures/move/ACC.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(False)
        self.label_3.setIndent(-4)
        self.label_3.setObjectName("label_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(570, 30, 71, 61))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../../../Pictures/move/images.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(940, 30, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(380, 40, 51, 51))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("../../../Pictures/move/NHA.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 30, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(860, 40, 71, 61))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../../../Pictures/move/tải xuống.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(70, 230, 441, 531))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(220, 30, 131, 31))
        self.comboBox.setObjectName("comboBox")

        # Trích xuất các giá trị duy nhất từ cột 'Outlook' của DataFrame
        outlook_values = self.df['Outlook'].unique()
        self.comboBox.insertItem(0, "")
        # Thêm các giá trị vào combobox
        for value in outlook_values:
            self.comboBox.addItem(value)


        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(60, 20, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(220, 100, 131, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        # Trích xuất các giá trị duy nhất từ cột 'Temp' của DataFrame
        temp_values = self.df['Temp'].unique()
        # Thêm mục trống vào combobox
        self.comboBox_2.insertItem(0, "")
        # Thêm các giá trị từ 'Temp' vào combobox
        for value in temp_values:
            self.comboBox_2.addItem(value)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame)
        self.comboBox_3.setGeometry(QtCore.QRect(220, 180, 131, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        # Trích xuất các giá trị duy nhất từ cột 'Humidity' của DataFrame
        humidity_values = self.df['Humidity'].unique()
        # Thêm mục trống vào combobox
        self.comboBox_3.insertItem(0, "")
        # Thêm các giá trị từ 'Humidity' vào combobox
        for value in humidity_values:
            self.comboBox_3.addItem(value)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame)
        self.comboBox_4.setGeometry(QtCore.QRect(220, 260, 131, 31))
        self.comboBox_4.setObjectName("comboBox_4")
        windy_column = self.df['Windy']

        # Trích xuất các giá trị duy nhất từ cột 'Windy'
        windy_values = windy_column.unique()

        # Chuyển đổi các giá trị từ kiểu numpy.bool_ thành chuỗi
        windy_values = [str(value) for value in windy_values]

        # Thêm mục trống vào combobox
        self.comboBox_4.insertItem(0, "")

        # Thêm các giá trị từ 'Windy' vào combobox
        for value in windy_values:
            self.comboBox_4.addItem(value)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(60, 90, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(60, 170, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(60, 240, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(80, 330, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(-10, 0, 16, 531))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setGeometry(QtCore.QRect(0, -10, 441, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(430, 0, 16, 531))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setGeometry(QtCore.QRect(0, 520, 441, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")

        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(550, 420, 141, 91))
        self.pushButton_4.clicked.connect(self.run_decision_tree)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(820, 420, 261, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1239, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.comboBox.currentIndexChanged.connect(self.updateListWidget)
        self.comboBox_2.currentIndexChanged.connect(self.updateListWidget)
        self.comboBox_3.currentIndexChanged.connect(self.updateListWidget)
        self.comboBox_4.currentIndexChanged.connect(self.updateListWidget)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "HOME"))
        self.pushButton_3.setText(_translate("MainWindow", "PREDICT"))
        self.pushButton_2.setText(_translate("MainWindow", "RECOMMED"))
        self.label_2.setText(_translate("MainWindow", "Thời tiết "))
        self.label_5.setText(_translate("MainWindow", "Khí hậu"))
        self.label_9.setText(_translate("MainWindow", "Độ ẩm"))
        self.label_10.setText(_translate("MainWindow", "Gió"))
        self.pushButton_4.setText(_translate("MainWindow", "Dự đoán"))
        self.label_4.setText(_translate("MainWindow", "Kết quả"))

    def updateListWidget(self):
        self.listWidget.clear()

        selected_values = []

        selected_values.append(self.comboBox.currentText())
        selected_values.append(self.comboBox_2.currentText())
        selected_values.append(self.comboBox_3.currentText())
        selected_values.append(self.comboBox_4.currentText())

        for value in selected_values:
            if value:
                item = QtWidgets.QListWidgetItem(value)
                self.listWidget.addItem(item)

    from sklearn.preprocessing import LabelEncoder
    from sklearn.tree import DecisionTreeClassifier
    import numpy as np

    def run_decision_tree(self):
        # Lấy dữ liệu từ các combobox
        outlook = self.comboBox.currentText()
        temp = self.comboBox_2.currentText()
        humidity = self.comboBox_3.currentText()
        windy = self.comboBox_4.currentText()
        # Chuyển đổi dữ liệu sang dạng số
        X = self.df[['Outlook', 'Temp', 'Humidity', 'Windy']]
        X.columns = ['Outlook', 'Temp', 'Humidity', 'Windy']
        y = self.df['go to the cinema']
        label_encoder = LabelEncoder()
        X.loc[:, 'Outlook'] = label_encoder.fit_transform(X['Outlook'])
        X.loc[:, 'Temp'] = label_encoder.fit_transform(X['Temp'])
        X.loc[:, 'Humidity'] = label_encoder.fit_transform(X['Humidity'])
        X.loc[:, 'Windy'] = label_encoder.fit_transform(X['Windy'])
        outlook = label_encoder.transform([outlook])[0]
        temp = label_encoder.transform([temp])[0]
        humidity = label_encoder.transform([humidity])[0]
        windy = label_encoder.transform([windy])[0]
        # Kiểm tra độ dài của X và y
        assert len(X) == len(y), "Lengths of X and y do not match"
        # Tạo và huấn luyện mô hình
        clf = DecisionTreeClassifier()
        clf.fit(X, y)
        # Đặt tên cho các đặc trưng
        clf.feature_names = ['Outlook', 'Temp', 'Humidity', 'Windy']
        # Dữ liệu kiểm tra
        X_test = np.array([[outlook, temp, humidity, windy]])
        # Dự đoán
        predicted_labels = clf.predict(X_test)
        # Hiển thị kết quả trên label_4
        result = "Không nên đi" if predicted_labels[0] == 1 else "Nên đi xem phim"
        self.label_4.setText(result)


app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec_())